language: r
warnings_are_errors: false
sudo: required
dist: trusty

r:
 - release
 - devel

apt_packages:
 - libxml2

r_packages:
 - xml2
 - testthat
 - covr
 - base64enc

after_success:
 - Rscript -e 'library(covr); codecov()'

notifications:
  email:
   on_success: change
   on_failure: change


