language: r
warnings_are_errors: false
sudo: required
dist: trusty
bio_required: true

r:
 - release
 - devel

apt_packages:
 - libxml2
 - libnetcdf-dev
 - udunits-bin
 - libudunits2-dev

r_packages:
 - xml2
 - testthat
 - covr

bioc_packages:
 - mzR

after_success:
 - Rscript -e 'library(covr); codecov()'

notifications:
  email:
   on_success: change
   on_failure: change


